

// AUTOGENERATED FILE

#ifndef FUR_GL_LOADER_H
#define FUR_GL_LOADER_H

#ifdef __cplusplus
extern C {
#endif

#include <core/macros.h>

#include <GL/gl.h>

#ifdef _WIN32
#include <windows.h>
#define APIENTRYP APIENTRY *
#include <GL/glext.h>
#endif

#define FUNC(name, ret_type, ...)                       \
    typedef ret_type (APIENTRYP name##_t)(__VA_ARGS__); \
    extern name##_t name

extern b8 fur_use_wayland;

void fur_render_gl_load(void);  

#ifdef _WIN32
FUNC(glActiveTexture, void, GLenum texture);
#endif


FUNC(glCreateShader, GLuint, GLenum type);
FUNC(glShaderSource, void, GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length);
FUNC(glCompileShader, void, GLuint shader);
FUNC(glGetShaderiv, void, GLuint shader, GLenum pname, GLint* params);
FUNC(glGetShaderInfoLog, void, GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infolog);
FUNC(glDeleteShader, void, GLuint shader);

FUNC(glCreateProgram, GLuint, void);
FUNC(glAttachShader, void, GLuint program, GLuint shader);
FUNC(glLinkProgram, void, GLuint program);
FUNC(glGetProgramiv, void, GLuint program, GLenum pname, GLint* params);
FUNC(glGetProgramInfoLog, void, GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
FUNC(glDeleteProgram, void, GLuint program);

FUNC(glGenVertexArrays, void, GLsizei n, GLuint* arrays);
FUNC(glGetUniformLocation, GLint, GLuint program, const GLchar* name);
FUNC(glGenBuffers, void, GLsizei n, GLuint* buffers);
FUNC(glBindBuffer, void, GLenum target, GLuint buffer);
FUNC(glBufferData, void, GLenum target, GLsizeiptr size, const void* data, GLenum usage);
FUNC(glTexBuffer, void, GLenum target, GLenum internalformat, GLuint buffer);

FUNC(glDeleteVertexArrays, void, GLsizei n, const GLuint* arrays);
FUNC(glDeleteBuffers, void, GLsizei n, const GLuint* buffers);

FUNC(glUseProgram, void, GLuint program);
FUNC(glBindVertexArray, void, GLuint array);
FUNC(glUniformMatrix4fv, void, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
FUNC(glBufferSubData, void, GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
FUNC(glUniform1i, void, GLint location, GLint v0);
FUNC(glUniform1f, void, GLint location, GLfloat v0);
FUNC(glDrawArraysInstanced, void, GLenum mode, GLint first, GLsizei count, GLsizei instancecount);

FUNC(glGenFramebuffers, void, GLsizei n, GLuint* framebuffers);
FUNC(glBindFramebuffer, void, GLenum target, GLuint framebuffer);
FUNC(glFramebufferTexture2D, void, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
FUNC(glCheckFramebufferStatus, GLenum, GLenum target);
FUNC(glDeleteFramebuffers, void, GLsizei n, GLuint* framebuffers);

FUNC(glGenRenderbuffers, void, GLsizei n, GLuint* renderbuffers);
FUNC(glBindRenderbuffer, void, GLenum target, GLuint renderbuffer);
FUNC(glRenderbufferStorage, void, GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
FUNC(glFramebufferRenderbuffer, void, GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
FUNC(glDeleteRenderbuffers, void, GLsizei n, const GLuint* renderbuffers);

FUNC(glDrawBuffers, void, GLsizei n, const GLenum* bufs);

#ifdef __cplusplus
}
#endif

#endif
